/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.adminControlls;

import Controllers.dataController;
import Controllers.salesController;
import Controllers.sessionController;
import Controllers.ticketController;
import Models.BoxCut;
import Models.Messages;
import Models.Sale;
import Views.commondialogs.printerService;
import java.util.Date;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ARTEMISA
 */
public class boxCutReport extends javax.swing.JDialog {

    /**
     * Creates new form saleReport
     */
    String Class = "boxCutReport";
    salesController DataBase = salesController.getInstance();
    Date Now = new Date();
    DefaultTableModel modelo;
    BoxCut boxcut;

    public boxCutReport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(sessionController.getInstance().getShowedFrame());
        this.setResizable(false);
    }

    public void setData(BoxCut boxcut) {
        this.boxcut = boxcut;
        lblIdReg.setText("Registro No." + this.boxcut.getId());
        lblSeller.setText("Creado por: " + this.boxcut.getUser());
        lblSaleDate.setText("Fecha de Registro: " + this.boxcut.getDateCreatedToString());
        lblSaleTime.setText("Hora de Registro: " + this.boxcut.getTimeCreatedToString());
        lblInCash.setText("En Caja: " + dataController.getInstance().getMoneyFormat(boxcut.getInCash()));
        lblToS.setText("Total en Ventas" + dataController.getInstance().getMoneyFormat(boxcut.getTotalOfSale()));
        btnClose.requestFocus();

        loadTable();
        showDatabase();
    }

    public void loadTable() {
        try {
            modelo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int filas, int columnas) {
                    if (columnas < 0) {
                        return true;
                    } else {
                        return false;
                    }
                }
            };
            modelo.addColumn("Codigo");
            modelo.addColumn("Vendedor");
            modelo.addColumn("Total Venta");
            modelo.addColumn("Fecha Venta");
            modelo.addColumn("Hora Venta");
            tblData.setModel(modelo);
            tblData.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception e) {
            new Messages().errorMessage(Class, "loadTable()", e);
        }
    }

    public void showDatabase() {
        modelo.setRowCount(0);
        try {
            List<Sale> Sales = DataBase.findSalesbyBoxCutId(boxcut.getId());
            if (!Sales.isEmpty()) {
                for (int i = 0; i < Sales.size(); i++) {
                    Sale temp = Sales.get(i);
                    String[] newRow = new String[6];
                    newRow[0] = temp.getId();
                    newRow[1] = temp.getSeller();
                    newRow[2] = dataController.getInstance().getMoneyFormat(temp.getTotalOfSale());
                    newRow[3] = temp.getDateCreatedToString();
                    newRow[4] = temp.getTimeCreatedToString();
                    modelo.addRow(newRow);
                }
            }
        } catch (Exception e) {
            new Messages().errorMessage(Class, "showDatabase()", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        lblIdReg = new javax.swing.JLabel();
        lblSeller = new javax.swing.JLabel();
        lblSaleDate = new javax.swing.JLabel();
        lblSaleTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblInCash = new javax.swing.JLabel();
        lblToS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("Reporte de Corte de Caja");

        btnClose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrint.setText("Imprimir");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblData.setRowHeight(30);
        jScrollPane1.setViewportView(tblData);

        lblIdReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIdReg.setText("IdReg");

        lblSeller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSeller.setText("Seller");

        lblSaleDate.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        lblSaleDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaleDate.setText("dateodSale");

        lblSaleTime.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        lblSaleTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaleTime.setText("TimeofSale");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ventas Registradas");

        lblInCash.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInCash.setText("En Caja");

        lblToS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblToS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblToS.setText("Total Of Sales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSaleDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSaleTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblIdReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblToS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaleDate)
                    .addComponent(lblSaleTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblInCash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblToS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnPrint))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        btnCancel();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        printDocument();
    }//GEN-LAST:event_btnPrintActionPerformed

    public void printDocument() {
        if (new Messages().yesNoMessage("Imprimir Venta", "Desea Imprimir Documento?")) {
            printerService selectPrinter = new printerService(sessionController.getInstance().getMainFrame(), true);
            selectPrinter.setData();
            selectPrinter.show();
            if (selectPrinter.isNext()) {
                String SelectedPrinter = selectPrinter.getSelectedPrinter();
                if (new ticketController().existBoxCur(boxcut)) {
                    System.out.println("existBoxCur");
                    if (new ticketController().rePrintBoxCut(boxcut, SelectedPrinter)) {
                        new Messages().aceptMessage("Imprimir Documento", "Documento Impreso Correctamente");
                    }
                } else {
                    System.out.println("createBoxCutPDF");
                    if (new ticketController().createBoxCutPDF(boxcut, SelectedPrinter)) {
                        new Messages().aceptMessage("Imprimir Documento", "Documento Impreso Correctamente");
                    }
                }
            }
        }
    }

    public void btnCancel() {
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boxCutReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boxCutReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boxCutReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boxCutReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                boxCutReport dialog = new boxCutReport(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdReg;
    private javax.swing.JLabel lblInCash;
    private javax.swing.JLabel lblSaleDate;
    private javax.swing.JLabel lblSaleTime;
    private javax.swing.JLabel lblSeller;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblToS;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
