/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.adminControlls;

import Controllers.dataController;
import Controllers.sessionController;
import Models.Messages;
import Models.Product;
import Views.userControlls.SelectProd;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author ATENEA
 */
public class setBulkCant extends javax.swing.JDialog {

    /**
     * Creates new form Granel
     */
    String Class = "setBulkCant";
    boolean next;
    Product Prod;
    double newCant = 0;

    public boolean isNext() {
        return next;
    }

    public void setNext(boolean next) {
        this.next = next;
    }

    public Product getProd() {
        return Prod;
    }

    public double getNewCant() {
        return newCant;
    }

    public void setNewCant(double newCant) {
        this.newCant = newCant;
    }

    public setBulkCant(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(sessionController.getInstance().getShowedFrame());
        this.setResizable(false);
        btnSelect.requestFocus();

        this.setFocusTraversalKeysEnabled(false);
        txtDesc.setFocusTraversalKeysEnabled(false);
        txtValue.setFocusTraversalKeysEnabled(false);
        txtInventory.setFocusTraversalKeysEnabled(false);
        btnSelect.setFocusTraversalKeysEnabled(false);
        rbtnCant.setFocusTraversalKeysEnabled(false);
        rbtnPrice.setFocusTraversalKeysEnabled(false);
        txtgetCant.setFocusTraversalKeysEnabled(false);
        txtgetValue.setFocusTraversalKeysEnabled(false);
        btnAgregar.setFocusTraversalKeysEnabled(false);
        btnCancel.setFocusTraversalKeysEnabled(false);

        txtgetCant.setTransferHandler(null);
        txtgetValue.setTransferHandler(null);
    }

    public void setData(Product Prod) {
        this.Prod = Prod;
        btnSelect.setEnabled(false);
        txtDesc.setText(this.Prod.getDescription());
        txtValue.setText(dataController.getInstance().getMoneyFormat(this.Prod.getValue()));
        txtInventory.setText(dataController.getInstance().getKgFormat(this.Prod.getInventory()));
        rbtnCant.setSelected(true);
//        txtgetCant.setText(this.Prod.getCant()+"");
    }

    public void setData() {
        rbtnCant.setEnabled(false);
        rbtnPrice.setEnabled(false);
        txtgetCant.setEnabled(false);
        txtgetValue.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpSelect = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        txtInventory = new javax.swing.JTextField();
        btnSelect = new javax.swing.JButton();
        pnlCalcGranel = new javax.swing.JPanel();
        txtgetValue = new javax.swing.JTextField();
        txtgetCant = new javax.swing.JTextField();
        rbtnPrice = new javax.swing.JRadioButton();
        rbtnCant = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PRODUCTO A GRANEL");

        txtDesc.setEditable(false);
        txtDesc.setColumns(20);
        txtDesc.setLineWrap(true);
        txtDesc.setRows(5);
        txtDesc.setText("SIN PRODUCTO SELECCIONADO");
        txtDesc.setWrapStyleWord(true);
        txtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtDesc);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("En Inventario");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Precio Unit");

        txtValue.setEditable(false);
        txtValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValue.setText("0.00");

        txtInventory.setEditable(false);
        txtInventory.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInventory.setText("0.00");

        btnSelect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelect.setText("SELECT");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        btnSelect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSelectKeyPressed(evt);
            }
        });

        txtgetValue.setEditable(false);
        txtgetValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtgetValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtgetValue.setText("0.00");
        txtgetValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgetValueActionPerformed(evt);
            }
        });
        txtgetValue.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtgetValuePropertyChange(evt);
            }
        });
        txtgetValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgetValueKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgetValueKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgetValueKeyTyped(evt);
            }
        });

        txtgetCant.setEditable(false);
        txtgetCant.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtgetCant.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtgetCant.setText("0.00");
        txtgetCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgetCantActionPerformed(evt);
            }
        });
        txtgetCant.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtgetCantPropertyChange(evt);
            }
        });
        txtgetCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgetCantKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgetCantKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgetCantKeyTyped(evt);
            }
        });

        btngrpSelect.add(rbtnPrice);
        rbtnPrice.setText("Por Precio");
        rbtnPrice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnPriceItemStateChanged(evt);
            }
        });
        rbtnPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPriceActionPerformed(evt);
            }
        });

        btngrpSelect.add(rbtnCant);
        rbtnCant.setText("Por Cantidad");
        rbtnCant.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnCantItemStateChanged(evt);
            }
        });
        rbtnCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCalcGranelLayout = new javax.swing.GroupLayout(pnlCalcGranel);
        pnlCalcGranel.setLayout(pnlCalcGranelLayout);
        pnlCalcGranelLayout.setHorizontalGroup(
            pnlCalcGranelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalcGranelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCalcGranelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCalcGranelLayout.createSequentialGroup()
                        .addComponent(rbtnCant)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCalcGranelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtgetCant)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCalcGranelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCalcGranelLayout.createSequentialGroup()
                        .addComponent(rbtnPrice)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCalcGranelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtgetValue)))
                .addContainerGap())
        );
        pnlCalcGranelLayout.setVerticalGroup(
            pnlCalcGranelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalcGranelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCalcGranelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCalcGranelLayout.createSequentialGroup()
                        .addComponent(rbtnCant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgetCant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCalcGranelLayout.createSequentialGroup()
                        .addComponent(rbtnPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgetValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 67, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtValue)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 62, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtInventory)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelect))
                            .addComponent(jScrollPane1)))
                    .addComponent(pnlCalcGranel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSelect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(pnlCalcGranel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnAgregar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        addToCart();
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void addToCart() {
        if (checkFields()) {
            setNext(true);
            this.dispose();
        }
    }

    public boolean hasValid() {
        boolean resp = false;
        if ((newCant > 0) && (newCant <= Prod.getInventory())) {
            resp = true;
        }
        return resp;
    }

    public boolean checkFields() {
        boolean resp = true;
        try {
            if (Prod == null) {
                btnSelect.requestFocus();
                resp = false;
            } else if (txtgetValue.getText().trim().length() < 1) {
                txtgetValue.setBackground(Color.yellow);
                txtgetValue.requestFocus();
                resp = false;
            } else if (txtgetCant.getText().trim().length() < 1) {
                txtgetCant.setBackground(Color.yellow);
                txtgetCant.requestFocus();
                resp = false;
            } else if (rbtnCant.isSelected() && !hasValid()) {
                txtgetCant.setBackground(Color.red);
                txtgetCant.requestFocus();
                resp = false;
            } else if (rbtnPrice.isSelected() && !hasValid()) {
                txtgetCant.setBackground(Color.red);
                rbtnPrice.setSelected(true);
                txtgetValue.requestFocus();
                resp = false;
            }
        } catch (Exception e) {
            new Messages().errorMessage(Class, "checkFields()", e);
        }

        return resp;
    }


    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        selectProd();
    }//GEN-LAST:event_btnSelectActionPerformed

    public void selectProd() {
        SelectProd sp = new SelectProd(null, true);
        sp.setData();
        sp.show();
        if (sp.isNext()) {
            Prod = sp.getResp();
            txtDesc.setText(this.Prod.getDescription());
            txtValue.setText(dataController.getInstance().getMoneyFormat(this.Prod.getValue()));
            txtInventory.setText(dataController.getInstance().getKgFormat(this.Prod.getInventory()));
            rbtnCant.setEnabled(true);
            rbtnPrice.setEnabled(true);
            txtgetCant.setEnabled(true);
            txtgetValue.setEnabled(true);
            rbtnCant.setSelected(true);
        }
    }

    private void txtgetCantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgetCantKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            rbtnPrice.setSelected(true);
        }
    }//GEN-LAST:event_txtgetCantKeyPressed

    private void txtgetValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgetValueKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            rbtnCant.setSelected(true);
        }
    }//GEN-LAST:event_txtgetValueKeyPressed

    private void btnSelectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSelectKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_btnSelectKeyPressed

    private void txtDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_txtDescKeyPressed

    private void txtgetCantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgetCantKeyReleased
        actionPreformed2();
    }//GEN-LAST:event_txtgetCantKeyReleased

    public void actionPreformed2() {
        if (txtgetCant.getText().trim().length() > 0) {
            txtgetCant.setBackground(Color.WHITE);
            if (txtgetCant.getText().equals(".")) {
                txtgetCant.setText("0.");
            }
        }
        recalcTotal();
    }

    private void txtgetValueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgetValueKeyReleased
        actionPreformed();
    }//GEN-LAST:event_txtgetValueKeyReleased

    public void actionPreformed() {
        if (!txtgetValue.getText().replace(" ", "").equals("")) {
            txtgetCant.setBackground(Color.WHITE);
            txtgetValue.setBackground(Color.WHITE);
            if (txtgetValue.getText().equals(".")) {
                txtgetValue.setText("0.");
            }
        }
        recalcTotal();
    }

    public void recalcTotal() {
        try {
            if (txtgetCant.getText().trim().length() > 0 && txtgetValue.getText().trim().length() > 0) {
                if (rbtnCant.isSelected()) {
                    double Cant = Double.parseDouble(txtgetCant.getText());
                    double Value = Prod.getValue();
                    double total = (Cant) * (Value);
                    newCant = Cant;
                    txtgetValue.setText(dataController.getInstance().getMoneyFormat(total));
                } else {
                    double punit = Prod.getValue();
                    double Value = Double.parseDouble(txtgetValue.getText());;
                    double total = (Value) / (punit);
                    newCant = total;
                    txtgetCant.setText(dataController.getInstance().getKgFormat(total));
                }
            } else {
                if (rbtnCant.isSelected()) {
                    newCant = 0;
                    txtgetValue.setText(dataController.getInstance().getMoneyFormat(0));
                } else {
                    newCant = 0;
                    txtgetCant.setText(dataController.getInstance().getKgFormat(0));
                }
            }
        } catch (Exception e) {
            new Messages().errorMessage(Class, "cartTotal()", e);
        }
    }

    private void txtgetCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgetCantKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtgetCant.getText().contains(".")) {
            evt.consume();
        }


    }//GEN-LAST:event_txtgetCantKeyTyped

    private void txtgetValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgetValueKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtgetValue.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtgetValueKeyTyped

    private void txtgetValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgetValueActionPerformed
        addToCart();
    }//GEN-LAST:event_txtgetValueActionPerformed

    private void txtgetCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgetCantActionPerformed
        addToCart();
    }//GEN-LAST:event_txtgetCantActionPerformed

    private void rbtnCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCantActionPerformed
//        txtgetCant.setText("");
//        txtgetCant.setBackground(Color.WHITE);
//        txtgetCant.setEditable(true);
//        txtgetCant.requestFocus();
//        txtgetValue.setEditable(false);
//        txtgetValue.setText("0");
//        txtgetValue.setBackground(Color.LIGHT_GRAY);
//        recalcTotal();
    }//GEN-LAST:event_rbtnCantActionPerformed

    private void rbtnPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPriceActionPerformed
//        txtgetValue.setText("");
//        txtgetValue.setEditable(true);
//        txtgetValue.setBackground(Color.WHITE);
//        txtgetValue.requestFocus();
//        txtgetCant.setEditable(false);
//        txtgetCant.setText("0");
//        txtgetCant.setBackground(Color.LIGHT_GRAY);
//        recalcTotal();
    }//GEN-LAST:event_rbtnPriceActionPerformed

    private void rbtnCantItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnCantItemStateChanged

        txtgetCant.setText("");
        txtgetCant.setBackground(Color.WHITE);
        txtgetCant.setEditable(true);
        txtgetCant.requestFocus();
        txtgetValue.setEditable(false);
        txtgetValue.setText("0");
        txtgetValue.setBackground(Color.LIGHT_GRAY);
        recalcTotal();
    }//GEN-LAST:event_rbtnCantItemStateChanged

    private void rbtnPriceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnPriceItemStateChanged

        txtgetValue.setText("");
        txtgetValue.setEditable(true);
        txtgetValue.setBackground(Color.WHITE);
        txtgetValue.requestFocus();
        txtgetCant.setEditable(false);
        txtgetCant.setText("0");
        txtgetCant.setBackground(Color.LIGHT_GRAY);
        recalcTotal();
    }//GEN-LAST:event_rbtnPriceItemStateChanged

    private void txtgetCantPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtgetCantPropertyChange
        txtgetCant.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtgetCantPropertyChange

    private void txtgetValuePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtgetValuePropertyChange
        txtgetValue.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtgetValuePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setBulkCant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setBulkCant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setBulkCant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setBulkCant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setBulkCant dialog = new setBulkCant(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSelect;
    private javax.swing.ButtonGroup btngrpSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCalcGranel;
    private javax.swing.JRadioButton rbtnCant;
    private javax.swing.JRadioButton rbtnPrice;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtInventory;
    private javax.swing.JTextField txtValue;
    private javax.swing.JTextField txtgetCant;
    private javax.swing.JTextField txtgetValue;
    // End of variables declaration//GEN-END:variables
}
