/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.messages;

import Controllers.sessionController;
import Controllers.systemController;
import Models.Messages;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.event.KeyEvent;
import java.util.Date;

/**
 *
 * @author OSBAL
 */
public class ErrorMessage extends javax.swing.JDialog implements ClipboardOwner {

    /**
     * Creates new form MensajeSiNo
     */
    sessionController session = sessionController.getInstance();
    String Exception;
    String Class;
    String Method;
    Date Reported;
    boolean resp;

    String fastReport;
    String fullReport;

    public boolean isResp() {
        return resp;
    }

    public void setResp(boolean resp) {
        this.resp = resp;
    }

    public void setData(String Class, String Method, Exception Exception) {
        lblTitulo.setText("Exception Recived");
        this.Exception = Exception.toString();
        this.Class = "Class: " + Class + ".java";
        this.Method = "Function: " + Method;
        this.Reported = new Date();

        fastReport = "***EXCEPTION REPORT***\n";
        fastReport += "-->" + Exception + "\n\n";
        fastReport += "***DATE OF ISSUE***" + "\n";
        fastReport += "-->" + this.Reported;

        fullReport = "***EXCEPTION REPORT***\n";
        fullReport += "-->" + Exception + "\n\n";
        fullReport += "***EXCEPTION CAUSED IN***" + "\n";
        fullReport += "-->" + this.Class + "\n";
        fullReport += "-->" + this.Method + "\n" + "\n";
        fullReport += "***CLIENT INFORMATION***" + "\n";
        fullReport += "-->Client: " + "STIL BE CONFIGURED" + "\n";
        fullReport += "-->Email: " + "STIL BE CONFIGURED" + "\n";
        fullReport += "-->Phone: " + "STIL BE CONFIGURED" + "\n" + "\n";
        fullReport += "***DATE OF ISSUE***" + "\n";
        fullReport += "-->" + this.Reported;

        if (session.getLogedUser() != null && session.getLogedUser().isRoot()) {
            btnReport.setVisible(false);
        } else {
            btnToClipboard.setVisible(false);
        }

        if (session.getLogedUser() != null && session.getLogedUser().isRoot()) {
            txtError.setText(fullReport);
        } else {
            txtError.setText(fastReport);
        }
        txtError.setCaretPosition(0);
    }

//    public ErrorMessage(java.awt.Frame parent, boolean modal) {
    public ErrorMessage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(sessionController.getInstance().getShowedFrame());
        this.setResizable(false);
        if (session.getLogedUser() != null && session.getLogedUser().isRoot()) {
            btnToClipboard.requestFocus();
        } else {
            btnReport.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        btnToClipboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnClose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        btnClose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCloseKeyPressed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReport.setText("Reportar");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        btnReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnReportKeyPressed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("TITULO");

        txtError.setEditable(false);
        txtError.setColumns(20);
        txtError.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txtError.setLineWrap(true);
        txtError.setRows(5);
        txtError.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtError);

        btnToClipboard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnToClipboard.setText("Copiar");
        btnToClipboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToClipboardActionPerformed(evt);
            }
        });
        btnToClipboard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnToClipboardKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnToClipboard, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnReport)
                    .addComponent(btnToClipboard))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        reportException();
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        btnCancel();
    }//GEN-LAST:event_btnCloseActionPerformed


    private void btnToClipboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToClipboardActionPerformed
        onClipboard();
    }//GEN-LAST:event_btnToClipboardActionPerformed

    private void btnCloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCloseKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnCancel();
        }

        if (evt.getKeyCode() == 37) {
            if (btnToClipboard.isVisible()) {
                btnToClipboard.requestFocus();
            } else {
                btnReport.requestFocus();
            }

        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnCancel();
        }
    }//GEN-LAST:event_btnCloseKeyPressed

    private void btnReportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnReportKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            btnCancel();
        }

        if (evt.getKeyCode() == 39) {
            btnClose.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            reportException();
        }
    }//GEN-LAST:event_btnReportKeyPressed

    private void btnToClipboardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnToClipboardKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            btnCancel();
        }

        if (evt.getKeyCode() == 39) {
            btnClose.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            reportException();
        }
    }//GEN-LAST:event_btnToClipboardKeyPressed

    public void reportException() {
        setClipboard(this.fullReport);
        String Mensaje = "Mensaje Copiado en Portapapeles," + "<br>";
        Mensaje += "Resolveremos el Incidente lo mas pronto posible..." + "<br>" + "<br>";
        Mensaje += "Gracias por tu Ayuda! ;)";
        new Messages().aceptMessage("Reportar Excepcion", Mensaje);
        getHelp();
        this.dispose();
    }

    public void getHelp() {
        systemController.getInstance().getContactPage();
    }

    public void onClipboard() {
        setClipboard(fullReport);
        new Messages().closeMessage("Copiar Mensaje", "Mensaje en Portapapeles");
    }

    public void btnCancel() {
        this.dispose();
    }

    public void setClipboard(String txt) {
        StringSelection text = new StringSelection(txt);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(text, this);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ErrorMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ErrorMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ErrorMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErrorMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ErrorMessage dialog = new ErrorMessage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnToClipboard;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtError;
    // End of variables declaration//GEN-END:variables

    @Override
    public void lostOwnership(Clipboard clpbrd, Transferable t) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
